### PR TITLE
hardware: Use Python 3

### PR DESCRIPTION
**Pull request by bantu**
Let's make @Cheffu happy.

### CODE REVIEW

**Comment by Peter42** [comment]
@imbalino could you check if https://github.com/WaeCo/Coffee-light/pull/29/commits/4587bcc253ca58e78d4500e1de2bcec1a4cba937 is really the only change needed to make it run in python3?

**Comment by bantu** [comment]
It was working fine during my testing.

The systemd service definition needs updating to not explicitly name `python` as the interpreter. Instead, it should point to `mySocket.py` such that its shebang is used. Then again, the service definition is not tracked in this repository right now (#30).

**Comment by bantu** [comment]
Rebased

**Comment by bantu** [comment]
Bump

**Pull request merged**
